-- Sequence
CREATE SEQUENCE DEFULT.BBS_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

-- Trigger
CREATE TRIGGER DEFULT.BBS_TRG
BEFORE INSERT
ON DEFULT.BBS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column IDX
  :new.IDX := BBS_SEQ.nextval;
END BBS_TRG;
/
