-- Sequence
CREATE SEQUENCE DEFULT.DEFULT_USER_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

-- Trigger
CREATE TRIGGER DEFULT.DEFULT_USER_TRG
BEFORE INSERT
ON DEFULT.DEFULT_USER
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column U_NO
  :new.U_NO := DEFULT_USER_SEQ.nextval;
END DEFULT_USER_TRG;
/
-- Sequence
CREATE SEQUENCE DEFULT.DEFULT_REPLY_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

-- Trigger
CREATE TRIGGER DEFULT.DEFULT_REPLY_TRG
BEFORE INSERT
ON DEFULT.DEFULT_REPLY
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column R_NO
  :new.R_NO := DEFULT_REPLY_SEQ.nextval;
END DEFULT_REPLY_TRG;
/
-- Sequence
CREATE SEQUENCE DEFULT.DEFULT_BOARD_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

-- Trigger
CREATE TRIGGER DEFULT.DEFULT_BOARD_TRG
BEFORE INSERT
ON DEFULT.DEFULT_BOARD
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column B_NO
  :new.B_NO := DEFULT_BOARD_SEQ.nextval;
END DEFULT_BOARD_TRG;
/

-- Sequence
CREATE SEQUENCE DEFULT.DEFULT_FILE_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

-- Trigger
CREATE TRIGGER DEFULT.DEFULT_FILE_TRG
BEFORE INSERT
ON DEFULT.DEFULT_FILE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column F_NO
  :new.F_NO := DEFULT_FILE_SEQ.nextval;
END DEFULT_FILE_TRG;
/
